# Generated by Django 2.2.7 on 2019-12-18 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('arrival', models.CharField(max_length=8, null=True, verbose_name='Arrival')),
                ('day', models.IntegerField(null=True, verbose_name='Day')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('departure', models.CharField(max_length=8, null=True, verbose_name='Departure')),
            ],
        ),
        migrations.CreateModel(
            name='Seat_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ac', models.IntegerField(verbose_name='1st AC')),
                ('second_ac', models.IntegerField(verbose_name='2nd AC')),
                ('third_ac', models.IntegerField(verbose_name='3rd AC')),
                ('sleeper', models.IntegerField(verbose_name='Sleeper')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('state', models.CharField(max_length=20, null=True, verbose_name='State')),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('zone', models.CharField(max_length=10, null=True, verbose_name='Zone')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('arrival', models.CharField(max_length=8, null=True, verbose_name='Arrival')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('zone', models.CharField(max_length=10, null=True, verbose_name='Zone')),
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Number')),
                ('departure', models.CharField(max_length=8, null=True, verbose_name='Departure')),
                ('return_train', models.CharField(max_length=15, null=True, verbose_name='Return Train')),
                ('duration_h', models.IntegerField(null=True, verbose_name='Duration Hours')),
                ('duration_m', models.IntegerField(null=True, verbose_name='Duration Minutes')),
                ('type', models.CharField(max_length=5, null=True, verbose_name='Type')),
                ('distance', models.IntegerField(null=True, verbose_name='Distance')),
                ('dest', models.ForeignKey(on_delete=models.SET(None), related_name='train_dest', to='myapp.Station')),
                ('source', models.ForeignKey(on_delete=models.SET(None), related_name='train_source', to='myapp.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=20, verbose_name='Name')),
                ('type', models.CharField(max_length=2, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('fare', models.IntegerField(verbose_name='Fare')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_tickets', to='myapp.Seat_Chart')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_tickets', to='myapp.Station')),
                ('dest_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_schedule_tickets', to='myapp.Schedule')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tickets', to='myapp.Station')),
                ('source_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_schedule_tickets', to='myapp.Schedule')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tickets', to='myapp.Train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='seat_chart',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_chart', to='myapp.Train'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_schedule', to='myapp.Station'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_schedule', to='myapp.Train'),
        ),
    ]
